export SplashScreen from './SplashScreen';
export StudentList from './StudentList';
export AddStudent from './AddStudent';
export Login from './Login';
export Language from './Language';
export Notifications from './Notifications';
export * from './VideoScreen';
export * from './Musicplayer';
export * from './SqliteDemo';
